name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build -t 246eedd7ea8b7e9cb52a24de7323bdf0db67708f44fcec9eb76901c459035cd0/wisecow-app:latest .
      - name: Push Docker image
        run: docker push 246eedd7ea8b7e9cb52a24de7323bdf0db67708f44fcec9eb76901c459035cd0/wisecow-app:latest
      - name: Deploy to Kubernetes
        run: kubectl apply -f wisecow-deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
